name: 'Terraform CI/CD con Infracost'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # ------ JOB PARA INFRACOST ------
  # Se ejecuta solo en Pull Requests para mostrar el impacto de los costos antes de fusionar.
  infracost:
    name: 'Análisis de Costos con Infracost'
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Permiso para escribir comentarios en el PR
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Run Infracost and Comment
        uses: infracost/actions/comment@v2
        with:
          path: ./terraform
          # Se usa la bandera corregida 'terraform-var-file' (singular).
          terraform-var-file: terraform.tfvars
          behavior: update

  # ------ JOB PARA APLICAR CAMBIOS ------
  # Se ejecuta solo cuando se hace push (o se fusiona un PR) a la rama 'main'.
  terraform-apply:
    name: 'Apply Terraform'
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      # --- CORRECCIÓN CRÍTICA AÑADIDA AQUÍ ---
      # Pasa el secret de la contraseña de la BD como una variable de entorno.
      # Esto evita que el 'apply' se quede esperando una entrada manual.
      env:
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}